### ISSUE TITLE
Add a date picker to the "Published At" field

### ISSUE THREAD

**Issue by carols10cents** [pgharts/trusty-cms#105]
This used to have a prototype date picker but now it has no date picker since we switched to jquery. I did a bit of research to try and find a JS library that would be lighter weight than pulling in all of jqueryUI, but I didn't find anything that stood out to me.

**Comment by krainboltgreene** [comment]
Is this still open or did @sinthetix fix this?

**Comment by fitzgerald** [comment]
Yes! This is closed. I just retested.
