### ISSUE TITLE
Update radiant references in Gemfile

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-cms#134]
https://github.com/pgharts/trusty-cms/blob/master/Gemfile

**Comment by krainboltgreene** [comment]
Is this simply a search/replace for "radiant-" to "trusty-"?

**Comment by fitzgerald** [comment]
Updated here:
https://github.com/pgharts/trusty-cms/pull/173/commits/35c745860d4049383b20738cde9d25b40d92e423

**Comment by fitzgerald** [comment]
This is done!
