### ISSUE TITLE
Change <title>Pages - Radiant CMS - Publishing for Small Teams</title>

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-cms#137]
It looks like when you log into the cms, the page title reads: Pages - Radiant CMS - Publishing for Small Teams

<title>Pages - Radiant CMS - Publishing for Small Teams</title>

Should be:
<title>Pages - TrustyCMS/title>

**Comment by krainboltgreene** [comment]
I can find a reference to "Publishing for Small Teams", but not a reference to "Radiant CMS", this might be a database-pulled information, or no longer present.

**Comment by fitzgerald** [comment]
This is an old ticket. Closing.
