### ISSUE TITLE
CKEditor doesn't retain selected editor after saving page

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-cms#139]
If you switch to source view, make some edits and save page, the CKEditor switches back to the wysiwyg editor. This is annoying for the end user. Ideally, the CKEditor would retain the source view if that is what the end user was using before saving.

**Comment by sipple** [comment]
Added jquery.cookie to the project and save the state of the editor there..

**Comment by sipple** [comment]
b3d66b78760a554d20c55a7f90eba4d83f55e5df
