### ISSUE TITLE
Update Contributors List

### ISSUE THREAD

**Issue by sipple** [pgharts/trusty-cms#141]
Hello, contributors! I'm tagging you on this because I'm about to make a public announcement about Trusty CMS' completion and want to be able to thank you all. But I want to make sure I credit you as you want to be credited (a thought I had, of course, *after* I added names to the Contributors file.)

So, take a look here: https://github.com/pgharts/trusty-cms/blob/master/CONTRIBUTORS.md

And if you'd like any changes to how you're being credited, let me know (or submit a pull request, or whatever) and I'll update things. I expect to send out the announcement next week.

@carols10cents @sinthetix @amcoder @justinxreese @fitzgerald @krainboltgreene @colindean

**Comment by colindean** [comment]
good for me :+1:

**Comment by justinxreese** [comment]
:+1:

**Comment by sinthetix** [comment]
Can you switch my last name to Fulton please? :smile:

**Comment by sipple** [comment]
@sinthetix: Done! Thank you!

**Comment by sinthetix** [comment]
@sipple Thanks, and, lol, your last fix for Patrick's last name has a typo too. I almost made a PR, haha. :smile_cat:

**Comment by sipple** [comment]
@sinthetix: Oof. Thank you again. Maybe I should back away from the keyboard before I cause any further damage.

**Comment by fitzgerald** [comment]
This is done!
