### ISSUE TITLE
Creating a page with a slug that already exists displays ugly error message

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-cms#142]
If you attempt to create a page that has the same slug as an existing page, it displays an ugly and confusing error message:
The change you wanted was rejected.
Maybe you tried to change something you didn't have access to.
![3-11-2015 11-51-35 am](https://cloud.githubusercontent.com/assets/177947/6600432/ec3ce71a-c7e5-11e4-936e-5164f3401417.jpg)

It should just validate the slug and have a user-friendly message like "A page with the same slug value already exists"

Here is a screenshot of the old radiant error, which is slightly less confusing.
![3-11-2015 11-59-52 am](https://cloud.githubusercontent.com/assets/177947/6600503/67afed7a-c7e6-11e4-8524-5c4176ad7bd8.jpg)

**Comment by krainboltgreene** [comment]
So amusingly this isn't an actual database rejection, like it sounds, this is the generic error message that displays with the CSRF token was either invalid or missing.

Ultimately this means that it's not about the slug and something awkward with your "state".
