### ISSUE TITLE
Ask Github to remove the Fork status to allow code search

### ISSUE THREAD

**Issue by krainboltgreene** [pgharts/trusty-cms#143]
Currently google doesn't allow code searching for Forked repositories (easier indexing on their part).

At this point while radiant is technically upstream trusty-cms is no longer *directly* forked from radiant CMS.

Also, I can fix issues easier from the browser if I can code search :P

**Comment by sipple** [comment]
@krainboltgreene, is that something I can just submit as a support request? I didn't know that was an option!

**Comment by krainboltgreene** [comment]
Yep,  just email support@github.com

**Comment by sipple** [comment]
I've emailed github support and will close this once this is done.

**Comment by sipple** [comment]
This has been taken care of!
