### ISSUE TITLE
Forgot password functionality

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-cms#162]
We've gotten requests to have a forgot password feature added to the trusty login page. It would be a nice enhancement to add this.

**Comment by wonderwoman13** [comment]
Delivered here: 

https://github.com/pgharts/trusty-cms/pull/164
https://github.com/pgharts/trusty-cms/pull/163

Released in version 2.0.21

👍  ⚡  💯

**Comment by wonderwoman13** [comment]
Delivered here:

#164
#163

Released in version 2.0.21

👍 ⚡ 💯
