### ISSUE TITLE
Review & Clean Up Unused Code Analysis

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-cms#172]
https://unused.codes/

[unused Analysis - TrustyCMS - 2016-08-17.txt](https://github.com/pgharts/trusty-cms/files/422607/unused.Analysis.-.TrustyCMS.-.2016-08-17.txt)

**Comment by wonderwoman13** [comment]
Half of the removals are here: 

https://github.com/pgharts/trusty-cms/pull/188
