### ISSUE TITLE
Assess all TODOs in code

### ISSUE THREAD

**Issue by carols10cents** [pgharts/trusty-cms#18]
Run `rake notes` or `git grep TODO`, then either delete them if they're no longer relevant, file new issues for them with what should be done, or do what they say to do if it's straightforward.

If those notes were added by Eric (@sipple, check `git blame` or `git log` for the file), talk with him to get his thoughts. If the notes were added by the radiant authors, see if there is information in the radiant commit logs or issues that would help in deciphering the note.

**Comment by fitzgerald** [comment]
Remaining TODOs are in third party files. Closing.
