### ISSUE TITLE
Collapse trusty-multi-site-extension into TrustyCMS

### ISSUE THREAD

**Issue by wonderwoman13** [pgharts/trusty-cms#249]

**Comment by dsatch** [comment]
Just wondering why this would go into the core... not something every user would want?

**Comment by wonderwoman13** [comment]
@dsatch, thank you for your question. For the users who are actively using the app, multi-site is a requirement. In an effort to streamline Rails upgrades and dependency management, it makes sense to bring all external extensions into TrustyCMS core. 

I've spec'ed out the work and it will bring minimal complexity to the codebase. For the CMS user, it is their choice to activate more than one site at once.
