### ISSUE TITLE
Deleting a site doesn't prompt user to confirm

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-cms#267]
When removing a site from the sites tab, the end user clicks _remove_.  There is no confirmation (cancel | delete) prompt. Given that deleting could cause some issues and accidental deletion could just maybe happen, we should add a confirmation prompt.

To repro:
Settings-->Sites
Click 'remove' next to any site

**Comment by danigirl329** [comment]
Changed to bug since the link has a confirm on it, but it's a deprecated attribute.
