### ISSUE TITLE
not able to migrate rails 5.2.0

### ISSUE THREAD

**Issue by moorem** [pgharts/trusty-cms#268]
Moorems-MacBook-Pro:gems moorem$ bundle exec rake db:bootstrap
(in /Users/moorem/projects/trusty)
This task will destroy any data in the database. Are you sure you want to 
continue? [yn] y
-- drop_table("ar_internal_metadata")
   -> 0.0098s
-- drop_table("schema_migrations")
   -> 0.0297s

Create the admin user (press enter for defaults).
Name (Administrator): admin
Username (admin): admin
Password (trusty): 
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Table 'trusty_blank_dev.users' doesn't exist: SHOW FULL FIELDS FROM `users`
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `_query'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `block in query'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:130:in `handle_interrupt'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:130:in `query'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:196:in `execute_and_free'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:804:in `column_definitions'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:113:in `columns'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/schema_cache.rb:69:in `columns'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/schema_cache.rb:75:in `columns_hash'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:466:in `load_schema!'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/attributes.rb:234:in `load_schema!'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:459:in `block in load_schema'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:456:in `load_schema'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:346:in `attribute_types'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:370:in `type_for_attribute'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/table_metadata.rb:33:in `type'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:55:in `build_bind_attribute'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder/basic_object_handler.rb:11:in `call'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:51:in `build'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:106:in `block in expand_from_hash'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:66:in `each'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:66:in `flat_map'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:66:in `expand_from_hash'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/where_clause_factory.rb:19:in `build'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/query_methods.rb:591:in `where!'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/query_methods.rb:584:in `where'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/finder_methods.rb:81:in `find_by'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/querying.rb:9:in `find_by'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/core.rb:187:in `find_by'
/Users/moorem/projects/trusty/vendor/gems/trusty-cms-3.3.2/lib/trusty_cms/setup.rb:39:in `create_admin_user'
/Users/moorem/projects/trusty/vendor/gems/trusty-cms-3.3.2/lib/trusty_cms/setup.rb:19:in `bootstrap'
/Users/moorem/projects/trusty/vendor/gems/trusty-cms-3.3.2/lib/trusty_cms/setup.rb:10:in `bootstrap'
/Users/moorem/projects/trusty/vendor/gems/trusty-cms-3.3.2/lib/tasks/database.rake:43:in `block (2 levels) in <top (required)>'
/Users/moorem/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/Users/moorem/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
Mysql2::Error: Table 'trusty_blank_dev.users' doesn't exist
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `_query'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:131:in `block in query'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:130:in `handle_interrupt'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/mysql2-0.5.1/lib/mysql2/client.rb:130:in `query'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:579:in `block (2 levels) in log'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:578:in `block in log'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_adapter.rb:569:in `log'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:196:in `execute_and_free'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:804:in `column_definitions'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:113:in `columns'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/schema_cache.rb:69:in `columns'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/connection_adapters/schema_cache.rb:75:in `columns_hash'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:466:in `load_schema!'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/attributes.rb:234:in `load_schema!'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/attribute_decorators.rb:51:in `load_schema!'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:459:in `block in load_schema'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:456:in `load_schema'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:346:in `attribute_types'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/model_schema.rb:370:in `type_for_attribute'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/table_metadata.rb:33:in `type'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:55:in `build_bind_attribute'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder/basic_object_handler.rb:11:in `call'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:51:in `build'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:106:in `block in expand_from_hash'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:66:in `each'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:66:in `flat_map'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:66:in `expand_from_hash'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/where_clause_factory.rb:19:in `build'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/query_methods.rb:591:in `where!'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/query_methods.rb:584:in `where'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/relation/finder_methods.rb:81:in `find_by'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/querying.rb:9:in `find_by'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activerecord-5.2.0/lib/active_record/core.rb:187:in `find_by'
/Users/moorem/projects/trusty/vendor/gems/trusty-cms-3.3.2/lib/trusty_cms/setup.rb:39:in `create_admin_user'
/Users/moorem/projects/trusty/vendor/gems/trusty-cms-3.3.2/lib/trusty_cms/setup.rb:19:in `bootstrap'
/Users/moorem/projects/trusty/vendor/gems/trusty-cms-3.3.2/lib/trusty_cms/setup.rb:10:in `bootstrap'
/Users/moorem/projects/trusty/vendor/gems/trusty-cms-3.3.2/lib/tasks/database.rake:43:in `block (2 levels) in <top (required)>'
/Users/moorem/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/Users/moorem/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:bootstrap
(See full trace by running task with --trace)
Moorems-MacBook-Pro:gems moorem$

**Comment by dsatch** [comment]
The layouts, clipped, multisites extensions are supposedly merged into the main repo, but something is apparently still missing to actually get them to work. I have Trusty 3.3.2 set up here http://trusty.ffaig7giym.us-west-2.elasticbeanstalk.com/admin/login
username: admin
password: admin

**Comment by wonderwoman13** [comment]
Hello, thanks for opening an issue. Migrations are running properly via the Trusty Bootstrap rake task in version 3.3.3.
