### ISSUE TITLE
Extensions integrated into core?

### ISSUE THREAD

**Issue by dsatch** [pgharts/trusty-cms#269]
The layouts, clipped, multisites extensions are supposedly merged into the main repo, but something is apparently still missing to actually get them to work. I have Trusty 3.3.3 set up here http://trusty.ffaig7giym.us-west-2.elasticbeanstalk.com/admin/login
username: Designer
password: designer

**Comment by wonderwoman13** [comment]
You are correct, they were added to Core but you still need to enable them in application.rb of your app. I'll include this in the next version of INSTALL.md. 

```
config.extensions = [ :snippets, :clipped, :layouts, :multi_site ]
```
