### ISSUE TITLE
Page body-field not present

### ISSUE THREAD

**Issue by dsatch** [pgharts/trusty-cms#271]
Have added
`config.extensions = [ :snippets, :clipped, :layouts, :multi_site ]`
to application.rb to get extensions working, now have assets and snippets tabs etc, thanks!
...but the page body is now non-functional. Anything I can do?

**Comment by wonderwoman13** [comment]
Hello @dsatch. I'm going to need more information, including steps you took, screenshots, logs etc. 

Here is what I see on a brand-new install. 

![screen shot 2018-05-03 at 9 07 03 am](https://user-images.githubusercontent.com/2446523/39578183-78f1137a-4eb1-11e8-86b1-b4262af5b667.png)

**Comment by dsatch** [comment]
OK, this appears to be a browser issue. Could you please check on firefox (mac)?
Thanks!

**Comment by wonderwoman13** [comment]
Hmm I logged into your instance on Firefox and CKEditor is rendering. 

Firefox version: 

![screen shot 2018-05-04 at 8 24 11 am](https://user-images.githubusercontent.com/2446523/39627661-a071cd90-4f74-11e8-913b-299c3e1915e6.png)

My Firefox is up to date on MacOS Sierra 

![screen shot 2018-05-04 at 8 25 11 am](https://user-images.githubusercontent.com/2446523/39627710-c15c05de-4f74-11e8-86d8-eba4da2778b1.png)

**Comment by dsatch** [comment]
OK thanks... I have Firefox Quantum 59.0.2, must be something to do with MacOS Yosemite. Appreciate your efforts, many thanks.
