### ISSUE TITLE
Radius tag <r:children> isn't working

### ISSUE THREAD

**Issue by dsatch** [pgharts/trusty-cms#273]
Renders:
wrong number of arguments (given 1, expected 0)
(See [http://trusty.ffaig7giym.us-west-2.elasticbeanstalk.com](http://trusty.ffaig7giym.us-west-2.elasticbeanstalk.com))

**Comment by wonderwoman13** [comment]
Thanks for filing the issue but in the future, please include the code snippet you are using. In this case, <r:children> was working but <r:children:each> was not. 

Resolved in version 3.3.4.
