### ISSUE TITLE
uninitialized constant LayoutsExtension::NestedLayouts (NameError)

### ISSUE THREAD

**Issue by thiyagarajan** [pgharts/trusty-cms#275]
while using layout extension getting following error

/Users/moorem/projects/trusty/trusty-cms/vendor/extensions/layouts-extension/layouts_extension.rb:11:in `activate': uninitialized constant LayoutsExtension::NestedLayouts (NameError)

#application.rb
config.extensions = [ :snippets, :clipped, :layouts, :multi_site ]

**Comment by wonderwoman13** [comment]
@thiyagarajan I will (please) need more information. What were you doing in the app when this error occurred? Creating a new Layout? Clicking on the Layouts tab?

**Comment by thiyagarajan** [comment]
This is error we are getting while start the application server after include 

#application.rb
config.extensions = [ :snippets, :clipped, :layouts, :multi_site ]

Steps to produce 
===================

1. Create rails application

2. Include the Trusty gem

3. Bundle

4.  add below line into application.rb
config.extensions = [ :snippets, :clipped, :layouts, :multi_site ]

try to start the server, we will get same error

/Users/moorem/projects/trusty/trusty-cms/vendor/extensions/layouts-extension/layouts_extension.rb:11:in `activate': uninitialized constant LayoutsExtension::NestedLayouts (NameError)

**Comment by wonderwoman13** [comment]
@thiyagarajan it sounds like you skipped running the Trusty CMS generator from the instructions in INSTALL.md.

**Comment by thiyagarajan** [comment]
We are not skipped any steps. sorry for late reply.

**Comment by wonderwoman13** [comment]
Hello, I just setup a new app, ran through the INSTALL.md instructions, ran Rails server, signed into Admin and create a new layout. It worked perfectly. 

Please start over on setting up your application. If you still have issues, please re-open this Issue with additional details.
