### ISSUE TITLE
rake aborted! NameError: uninitialized constant LayoutsExtension::NestedLayouts

### ISSUE THREAD

**Issue by moorem** [pgharts/trusty-cms#278]
We followed install.md
 Rails 5.2 and latest trusty cms

1) Moorems-MacBook-Pro:trusty moorem$ rails g trusty_cms trusty
Running via Spring preloader in process 19222
   identical  Rakefile
   identical  config.ru
   identical  config/boot.rb
   identical  config/environment.rb
   identical  config/application.rb
   identical  config/compass.rb
   identical  config/preinitializer.rb
   identical  config/routes.rb
    conflict  config/database.yml
Overwrite /Users/moorem/Desktop/trusty/config/database.yml? (enter "h" for help) [Ynaqdh] Y
       force  config/database.yml
   identical  config/environments/development.rb
   identical  config/environments/test.rb
   identical  config/environments/production.rb
   identical  config/initializers/trusty_cms_config.rb
   identical  config/initializers/secret_token.rb
   identical  config/initializers/session_store.rb
      remove  app/controllers/application_controller.rb
      remove  app/helpers/application_helper.rb
      remove  app/assets/javascripts/application.js
      remove  app/views/layouts/application.html.erb

2) add config.extensions = [ :snippets, :clipped, :layouts, :multi_site ] to enable them in application.rb

3) Moorems-MacBook-Pro:trusty moorem$ bundle exec rake db:setup
rake aborted!
NameError: uninitialized constant LayoutsExtension::NestedLayouts
/Users/moorem/Desktop/trusty-cms/vendor/extensions/layouts-extension/layouts_extension.rb:11:in `activate'
/Users/moorem/Desktop/trusty-cms/lib/simpleton.rb:16:in `method_missing'
/Users/moorem/Desktop/trusty-cms/lib/trusty_cms/extension_loader.rb:109:in `each'
/Users/moorem/Desktop/trusty-cms/lib/trusty_cms/extension_loader.rb:109:in `activate_extensions'
/Users/moorem/Desktop/trusty/config/application.rb:144:in `block in <class:Application>'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:62:in `with_execution_control'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:67:in `execute_hook'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:51:in `each'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/activesupport-5.2.0/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application/finisher.rb:75:in `block in <module:Finisher>'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `instance_exec'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:32:in `run'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/initializable.rb:60:in `run_initializers'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application.rb:361:in `initialize!'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `public_send'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/railtie.rb:190:in `method_missing'
/Users/moorem/Desktop/trusty/config/environment.rb:5:in `<top (required)>'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application.rb:337:in `require_environment!'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/railties-5.2.0/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/Users/moorem/.rvm/gems/ruby-2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/moorem/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/Users/moorem/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:setup => db:schema:load_if_ruby => db:create => db:load_config => environment
(See full trace by running task with --trace)

**Comment by wonderwoman13** [comment]
@moorem is your code opensourced? If yes, please link me to repository so I can clone it.

**Comment by wonderwoman13** [comment]
@moorem I cloned down your code and was able to run both of the setup rake tasks on Ruby version 2.5.0 successfully. I noted that you are pointing to Trusty locally: 

https://github.com/moorem/trusty/blob/master/Gemfile#L39

Unfortunately, I can't help you troubleshoot if you are not using the deployed gem.
