### ISSUE TITLE
You may have encountered a bug in the Ruby interpreter or extension libraries.

### ISSUE THREAD

**Issue by saydulk** [pgharts/trusty-cms#279]
[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Aborted
![screenshot from 2018-07-05 15 36 29](https://user-images.githubusercontent.com/1058663/42315480-6065a49e-8069-11e8-9074-aedb08418356.png)

**Comment by wonderwoman13** [comment]
Thank you for reporting the issue @saydulk. Can you please tell me the following: 

1. What were you trying to run? I can see the stack trace but not the original request you made from the command line. 

2. What Ruby version are you using ($ ruby -v)?

**Comment by saydulk** [comment]
phantomjs --version
-bash: /usr/local/bin/phantomjs: cannot execute binary file: Exec format error
![screenshot from 2018-07-05 19 01 50](https://user-images.githubusercontent.com/1058663/42324762-e6305616-8085-11e8-8b52-680b82a93c61.png)

**Comment by wonderwoman13** [comment]
@saydulk TrustyCMS is meant to be setup as a Ruby on Rails project using the included INSTALL.md file in the repository -- not using a Linux distro. PhantomJS is not a runtime dependency.

**Comment by saydulk** [comment]
ok, that means if I can run any rails app I can also setup TrustyCMS using INSTALL.md file? 
I have deploy a rails app over here- http://206.189.71.203:3000/

![screenshot from 2018-07-06 01 08 07](https://user-images.githubusercontent.com/1058663/42342836-1910766e-80b9-11e8-8a8a-da19a1742fb1.png)
