### ISSUE TITLE
Remove old deprecation notices

### ISSUE THREAD

**Issue by carols10cents** [pgharts/trusty-cms#49]
It looks like there are some `ActiveSupport::Deprecation` notices that radiant raises for things they deprecated. Some of these reference version 0.9.x of radiant, while this fork started from 1.1.4.

I think we can just remove most of these (and any relevant code that is no longer used anywhere) and shrink the code we have to support a little more.

These can be found by doing `git grep Deprecation`. Example from app/controllers/admin/resource_controller.rb:

```
    def announce_removed
      ActiveSupport::Deprecation.warn("announce_removed is no longer encouraged in TrustyCms 0.9.x.", caller)
      flash[:notice] = t("resource_controller.removed", :humanized_model_name => humanized_model_name)    
    end
```

The `announce_removed` method isn't called anywhere in trusty-cms's code. So this whole method can just go.

**Comment by wonderwoman13** [comment]
All deprecations were cleared as of the Trusty CMS Rails 5.1 upgrade.
