### ISSUE TITLE
Asset Search Upgrade: Searching for asset from a page fails

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-cms#744]
The new asset search feature does not work when initiated from a specific page. The pagination displays an error and the search feature navigates away from the page

**To Reproduce**
1. Go to to any page in the CMS
2. Click on Assets
3. Search for a word, like "Test" OR just click the pagination

**Comment by danigirl329** [comment]
Enhanced search by implementing the ransack gem to help with searching the assets database table as well as adding a timeout for autocomplete so that it doesn't fail due to a race condition.
